apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/instance: default
    app.kubernetes.io/component: webserver