apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-resource-quotas
spec:
  hard:
    count/configmaps: "100"
    count/cronjobs.batch: "20"
    count/jobs.batch: "100"
    count/persistentvolumeclaims: "20"
    count/pods: "25"
    count/replicationcontrollers: "30"
    count/secrets: "20"
    count/services: "20"
    limits.cpu: 1
    limits.memory: 2Gi
    requests.cpu: 200m
    requests.memory: 1Gi
    services.loadbalancers: "10"
    services.nodeports: "10"