namespace: dev-demo-highavailability-ns

bases:
- ../dev-common
- ../../base-ingress
- ../../base-deployment

patches:
- path: ingress-patch.yaml
  target:
    version: v1
    kind: Ingress
    group: networking.k8s.io
    name: helloworld-ingress

images:
- name: helloworld-webserver:1.0.0
  newTag: 1.0.0
