resources:
- networkpolicy.yaml
- cronjob.yaml
- role.yaml
- rolebinding.yaml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: nginx-conf
  files:
  - configmaps/nginx.conf