apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: content-updater
subjects:
- kind: User
  name: system:serviceaccount:placeholder:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: content-updater
  apiGroup: rbac.authorization.k8s.io