namespace: local-demo-highavailability-ns

bases:
- ../local-common
- ../../base-ingress
- ../../base-deployment

patches:
- path: remove-hostname-antiaffinity-patch.yaml
  target:
    version: v1
    kind: Deployment
    group: apps
    name: helloworld-deployment
- path: remove-topologyspreadconstraint-patch.yaml
  target:
    version: v1
    kind: Deployment
    group: apps
    name: helloworld-deployment
- path: ingress-patch.yaml
  target:
    version: v1
    kind: Ingress
    group: networking.k8s.io
    name: helloworld-ingress

images:
- name: helloworld-webserver
  newTag: 1.0.0